Feature
splunk-soar-connectors/darktrace pull request #2
Opened 2022-07-26 09:52 UTC by pdesai-crest

Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

## Pull Request Checklist

#### Please check if your PR fulfills the following requirements:
- [ ] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
## Pull Request Type

#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

2022-07-28 06:03 UTC, mishalp-crest commented
@AbrahamAjuelos, Can you please fix code-related linting and static tests failures like min_number_log_statements, product_name_on_files etc

2022-07-28 10:45 UTC, AbrahamAjuelos commented
@mishalp-crest Can you provide some instructions on how to fix the following issues:

- min_number_log_statements: Not sure why it would complain when we have the relevant functions using save progress constantly.
- minimal data paths
- expected_app_id
- sequential_order
- verbose_periods

2022-07-28 12:32 UTC, mishalp-crest commented
@AbrahamAjuelos 

For min_number_log_statements you can refer [this](https://github.com/splunk-soar-connectors/digitalshadows/pull/2/files#diff-bead98343fbbaf3c519e806bca093fd56ef379f6e24db4e472791d17e7dd0716R116)

I'll resolve other failures. 

Also kindly resolve linting failures too.

2022-08-08 15:40 UTC, AbrahamAjuelos commented
@mishalp-crest 

Remaining tasks:

1. min_number_log_statements: the test will be updated from your side to pick subdirectory information. Noted as expected failure for now.

2. Remaining tests: minimal_data_paths, repo_name_has_expected_app_id and sequential_order. Can you help with these ones as we are unsure on what specifically needs to be actioned?

2022-08-09 11:48 UTC, mmomin-crest approved these changes

2022-08-09 11:59 UTC, mishalp-crest commented
**Note:**
In static failure,
1. min_number_log_statements - This is an expected failure, already discussed this with Matt
2. repo_name_has_expected_app_id and app_actions - These failures will be passed after the app release MR will be merged

2022-08-17 03:44 UTC, joshquerinphantom requested changes

2022-08-17 03:44 UTC, joshquerinphantom commented on darktrace.json
> +    "app_version": "1.0.2",
Would it be possible to re-order the .json file to have the app info at the top? I don't think it's strictly necessary, but would be nice. Specifically, move everything from line 1056 and below to the top. i.e.

- App info
- Asset config
- PIP wheels
- Action definitions, etc.

2022-08-17 03:57 UTC, joshquerinphantom approved these changes

2022-08-17 04:00 UTC, merged